name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
       - 'gh_pages'
  
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy to'
        required: true
        default: 'gh-pages'
      folder:
        description: 'Folder to deploy'
        required: true
        default: 'gh_pages/dist'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }} 

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      
      - name: Clean static directory
        run: |
          echo "Configuring bot user..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@users.noreply.github.com"
          echo "Checking for static/js directory..."
          if [ -d "static/js" ]; then
            echo "Deleting old static JavaScript files..."
            rm -rf static/js*
            echo "Committing changes..."
            git add static
            git commit -m "Clean static directory"
            git push origin gh-pages
          else
            echo "No static directory found"
          fi
          echo "Done."

      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          cache: 'npm'
          cache-dependency-path: ./gh_pages/package-lock.json

      - name: Install and Build
        run: |
          cd gh_pages
          npm ci
          npm run build
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: ./gh_pages/dist